DATA:
  data_root: dataset/flickr25k/photos
  dataset_init: txt_mappings
  data_name: flickr25k_photos
  classes: 250
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

TRAIN:
  layer_types: [san, san, san, san, san]
  sa_type: 1
  widths: [64, 256, 512, 1024, 2048]
  layers: [2, 1, 1, 2, 1]
  added_nl_blocks: [0, 0, 1, 2, 0]
  ignore_label: 2000
  train_gpu: [0, 1]
  workers: 2
  batch_size: 64
  batch_size_val: 32
  base_lr: 0.1
  epochs: 100
  start_epoch: 0
  step_epochs: [30, 60, 90]
  label_smoothing: 0.1
  mixup_alpha:
  scheduler: cosine
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: exp/flickr25k_photos/san10_patchwise_nl/model
  weight:
  resume:
  time_breakdown: True
  evaluate: True
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  use_val_set: True
  test_gpu: [0]
  test_workers: 2
  batch_size_test: 100
  model_path: exp/flickr25k_photos/san10_patchwise_nl/model/model_best.pth