DATA:
  data_root: dataset/miniQuickDraw
  dataset_init: preprocessed_paths
  data_name: mini_quickdraw
  classes: 300
  mean: [0.1307]
  std: [0.3081]

TRAIN:
  arch: san
  sa_type: 0
  layers: [2, 1, 2, 4, 1]
  kernels: [3, 7, 7, 7, 7]
  ignore_label: 2000
  train_gpu: [0, 1]
  workers: 2
  batch_size: 64
  batch_size_val: 32
  base_lr: 0.1
  epochs: 40
  start_epoch: 0
  step_epochs: [30, 60, 90]
  label_smoothing: 0.1
  mixup_alpha:
  scheduler: cosine
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: exp/mini_quickdraw/san10_pairwise/model
  weight:
  resume:
  evaluate: True
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  use_val_set: True
  test_gpu: [0]
  test_workers: 2
  batch_size_test: 100
  model_path: exp/mini_quickdraw/san10_pairwise/model/model_best.pth