DATA:
  data_root: dataset/MNIST
  data_name: mnist
  classes: 10
  mean: [0.1307]
  std: [0.3081]
  channels: 1
  split: 2

TRAIN:
  arch: resnet
  widths: [256, 512, 1024, 2048] 
  layers: [1, 2, 4, 1]
  ignore_label: 2000
  train_gpu: [0]
  workers: 2
  batch_size: 32
  batch_size_val: 16 
  base_lr: 0.1
  epochs: 10
  start_epoch: 0
  step_epochs: [3, 6, 9]
  label_smoothing: 0.1
  mixup_alpha:
  scheduler: cosine
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  save_path: exp/mnist/resnet26/model
  weight:
  resume:
  evaluate: True
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: False
  world_size: 1
  rank: 0

TEST:
  test_gpu: [0]
  test_workers: 10
  batch_size_test: 100
  model_path: exp/mnist/resnet26/model/model_best.pth